apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-
  namespace: diploe2-lfcz
spec:
  taskRef:
    kind: Task
    name: git-clone
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
  - name: url
    value: "https://github.com/FerCz2489/pois-api"
  - name: deleteExisting
    value: "true"
  workspaces:
  - name: output
    persistentVolumeClaim:
      claimName: workspace

