apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace
  namespace: diploe2-lfcz  # Reemplaza con tu namespace real
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

