apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pois-api
  namespace: diplomado-fer 
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - image: docker.io/fercz/pois-api:v1.3
          ports:
            - containerPort: 8080
          env:  
            - name: MONGO_URI
              value: "mongodb+srv://geomatica_user:58VCQW84myk1Yc64@cluster0.s7t3a.mongodb.net/geomatica_db"
            - name: SERVER_PORT
              value: "8080"
  traffic:
    - percent: 100

