apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pois-api
  namespace: diplomado-fer 
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - image: docker.io/fercz/pois-api:v1.3
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret    # Usando el nombre de tu secreto
                  key: uri              # La clave dentro del secreto que contiene la URI
  traffic:
    - percent: 100

