apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-rolebinding
  namespace: diploe2-lfcz 
subjects:
  - kind: ServiceAccount
    name: tekton-sa
    namespace: diploe2-lfcz
roleRef:
  kind: Role
  name: tekton-role
  apiGroup: rbac.authorization.k8s.io

