apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
  namespace: diploe2-lfcz
secrets:
  - name: dockerconfig-secret
  - name: mongo-secret
imagePullSecrets:
  - name: dockerconfig-secret
