apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: maven-build-
  namespace: diploe2-lfcz  
spec:
  taskRef:
    kind: Task
    name: maven
  params:
    - name: GOALS
      value:
        - -B
        - -DskipTests
        - clean
        - package
    - name: MAVEN_IMAGE
      value: gcr.io/cloud-builders/mvn
    - name: CONTEXT_DIR
      value: "."
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: workspace
    - name: maven-settings
      configMap:
        name: maven-settings

