apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: buildah-run-
  namespace: diploe2-lfcz
spec:
  taskRef:
    name: buildah
  serviceAccountName: tekton-sa
  params:
    - name: IMAGE
      value: "docker.io/fercz/pois-api:latest"
    - name: TLSVERIFY
      value: "false"
    - name: STORAGE_DRIVER
      value: "vfs"
    - name: CONTEXT
      value: "."
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: workspace

