apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-hello-world
spec:
  description: |
    This pipeline demonstrates how a Tekton Pipeline works.
    Tasks in the pipeline:
    - echo: Prints a welcome message.
    - git-clone: Fetches a Git repository.
    - goodbye: Prints a completion message.
  params:
    - name: your-name
      type: string
    - name: repo-url
      type: string
  workspaces:
    - name: empty-dir
  tasks:
    - name: hello
      taskRef:
        name: task-echo
      params:
        - name: message
          value: "Hello $(params.your-name)"
    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: empty-dir
    - name: goodbye
      runAfter:
        - git-clone
      taskSpec:
        steps:
          - name: default
            image: busybox
            script: |
              echo "My first pipeline is done and executed!"
